name       : ghc
version    : 8.2.2
release    : 5
source     :
    - https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-src.tar.xz : bb8ec3634aa132d09faa270bbd604b82dfa61f04855655af6f9d14a9eedc05fc
    - https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-testsuite.tar.xz : 927ff939f46a0f79aa87e16e56e0a024a288c78259bed874cb15aa96a653566c
license    : BSD-3-Clause
component  : programming.haskell
summary    : The Glasgow Haskell Compiler
description: |
    The Glasgow Haskell Compiler
builddeps  :
    - ghc-devel
    - haskell-cabal-install
setup      : |
    cp $pkgfiles/build.mk mk/
    tar xvf $sources/ghc-$version-testsuite.tar.xz  --strip 1
    ./boot
    ./configure --prefix=/usr --libdir=/usr/lib64
build      : |
    %make V=0
install    : |
    %make_install
