name       : ghc
version    : 9.2.8
release    : 10
source     :
    - https://downloads.haskell.org/~ghc/9.2.8/ghc-9.2.8-src.tar.xz : 5f13d1786bf4fd12f4b45faa37abedb5bb3f36d5e58f7da5307e8bfe88a567a1
    - https://downloads.haskell.org/~ghc/9.2.8/ghc-9.2.8-testsuite.tar.xz : 4588f913f544e20e4c285f7d87ebc2181544ca680549f9eafed2a5cd19e4b532
license    : BSD-3-Clause
component  : programming.haskell
summary    : The Glasgow Haskell Compiler
description: |
    The Glasgow Haskell Compiler
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - libffi-devel
        - ncurses-devel
setup      : |
    cp $pkgfiles/build.mk mk/
    tar xvf $sources/ghc-$version-testsuite.tar.xz  --strip 1
    ./boot
    %configure --host=x86_64-unknown-linux \
               --target=x86_64-unknown-linux \
               --build=x86_64-unknown-linux \
               --with-system-libffi \
               --with-ffi-includes="$(pkg-config --variable=includedir libffi)"
build      : |
    %make V=0
install    : |
    %make_install

    # This will be generated by usysconf
    rm $installdir/%libdir%/ghc-*/package.conf.d/package.cache*
