name       : ghc
version    : 8.10.7
release    : 9
source     :
    - https://downloads.haskell.org/~ghc/8.10.7/ghc-8.10.7-src.tar.xz : e3eef6229ce9908dfe1ea41436befb0455fefb1932559e860ad4c606b0d03c9d
    - https://downloads.haskell.org/~ghc/8.10.7/ghc-8.10.7-testsuite.tar.xz : df8627dc50b9182dec96085afeb005ccf5a0adc56c40340330a5df65de2b82fe
license    : BSD-3-Clause
component  : programming.haskell
summary    : The Glasgow Haskell Compiler
description: |
    The Glasgow Haskell Compiler
builddeps  :
    - ghc-devel
    - haskell-cabal-install
setup      : |
    cp $pkgfiles/build.mk mk/
    tar xvf $sources/ghc-$version-testsuite.tar.xz  --strip 1
    ./boot
    %configure --host=x86_64-unknown-linux \
               --target=x86_64-unknown-linux \
               --build=x86_64-unknown-linux \
               --with-system-libffi \
               --with-ffi-includes="$(pkg-config --variable=includedir libffi)"
build      : |
    %make V=0
install    : |
    %make_install
patterns   :
    - docs :
        - /usr/lib64/*/html
