name       : ghc
version    : 8.0.1
release    : 1
source     :
    - http://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-src.tar.xz : 90fb20cd8712e3c0fbeb2eac8dab6894404c21569746655b9b12ca9684c7d1d2
    - http://downloads.haskell.org/~ghc/8.0-latest/ghc-8.0.1-x86_64-deb8-linux.tar.xz : b1c06af49b29521d5b122ef3311f5843e342db8b1769ea7c602cc16d66098ced
license    : BSD-3-Clause
component  : programming
summary    : The Glasgow Haskell Compiler
description: |
    The Glasgow Haskell Compiler
setup      : |
    tar -xvf $sources/ghc-8.0.1-x86_64-deb8-linux.tar.xz
    cd ghc-8.0.1
    ln -s /usr/lib64/libncursesw.so.5 /usr/lib64/libtinfo.so.5
    ./configure --prefix=/usr --libdir=/usr/lib64
    make install
    cd ..
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
