name       : ghc
version    : 8.0.1
release    : 4
source     :
    - http://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-src.tar.xz : 90fb20cd8712e3c0fbeb2eac8dab6894404c21569746655b9b12ca9684c7d1d2
license    : BSD-3-Clause
component  : programming.haskell
summary    : The Glasgow Haskell Compiler
description: |
    The Glasgow Haskell Compiler
builddeps  :
    - ghc
setup      : |
    ./configure --prefix=/usr --libdir=/usr/lib64
build      : |
    %make
install    : |
    %make_install
